version: '3'

services:
  registry:
    image: registry:2
    container_name: my_registry
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - registry_data:/var/lib/registry

  api:
    build:
      context: ./simple_api  # Remplace par le dossier de ton API
      dockerfile: Dockerfile
    image: localhost:5000/student_api
    container_name: student_api
    restart: always
    ports:
      - "5001:5000"
    depends_on:
      - registry

volumes:
  registry_data:
